Proyecto final
ElizaMejia/Curso-CSS pull request #16
Opened 2024-05-08 21:14 UTC by ElizaMejia

Se envia el PR en el que se subió el archivo HTML en el que se utiliza CSS para poder hacer uso de los elementos del capitulo, se esperan comentarios y retroalimentación.

2024-05-09 15:55 UTC, semanticmx commented
@ElizaMejia podrías agregar a @IIKUYY al proyecto para que revise también los comentarios?

2024-05-09 15:55 UTC, semanticmx requested changes

2024-05-09 15:55 UTC, semanticmx commented on ProyectoFinal/ProyectoCSS.html
> +<!DOCTYPE html>
@ElizaMejia vamos a renombrar el archivo a index.html para que al igual que el README.md tome el archivo como default al cargarlo desde el navegador.

2024-05-09 17:13 UTC, semanticmx requested changes

2024-05-09 17:13 UTC, semanticmx commented on ProyectoFinal/ProyectoCSS.html
> +             <img src="Logo.png">
vamos a estructurar el proyecto de forma que el directorio principal tenga un index.html y al mismo nivel exista un folder assets.

Dentro de este folder podemos incluir un subfolder para "images" donde vamos a colocar los archivos de imágen solamente.

Es decir:
```
\_
 \_index.html
 \_assets
 \_assets
          \_main.css
          \_main.js
          \_images
               \_logo.png
```

2024-05-09 17:13 UTC, semanticmx commented on ProyectoFinal/ProyectoCSS.html
> +             <img src="Logo.png">
de la misma forma vamos a utilizar kebab-case para el nombre de los archivos, entonces Logo.png se renombraría a logo.png

2024-12-11 19:31 UTC, ElizaMejia commented on ProyectoFinal/ProyectoCSS.html
> +<!DOCTYPE html>
Listo!

2024-12-12 17:38 UTC, semanticmx approved these changes
vamos a mezclarlo y ver como se ve en main

2025-01-14 18:17 UTC, merged